name: HTML Validator

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  html5validator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: HTML5Validator
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: /github/workspace
        log_level: INFO
        css: true
        skip_git_check: true
      continue-on-error: true

    - uses: actions/checkout@v3

    - name: Plain Test
      uses: ./
      with:
        root: tests/valid/

    - name: Testing Options
      id: valid
      uses: ./
      with:
        root: tests/valid/
        format: json
        log_level: INFO
        extra: -lll
        css: true

    - name: Test config
      id: config
      uses: ./
      with:
        config: tests/example_config.yaml

    - name: Check Blacklist
      id: blacklist
      uses: ./
      with:
        root: tests/
        blacklist: invalid

    - name: Check Failure
      id: invalid
      uses: ./
      with:
        root: tests/invalid/
        log_level: INFO
        css: true
      continue-on-error: true

    - name: Check Empty
      id: empty
      uses: ./
      with:
        log_level: INFO
        css: true
      continue-on-error: true

    - uses: actions/upload-artifact@v3
      with:
        name: log
        path: log.log
