name: HTML Validator

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  html5validator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: HTML5Validator
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: ./
        css: true
        log_level: INFO
